/**
 * Word boost passed to AssemblyAI to improve recognition accuracy on
 * pediatric medical terminology. Drawn from common peds-primary-care
 * encounters: developmental milestones, vaccines, common diagnoses,
 * common medications, anatomy. Sized conservatively — AssemblyAI caps
 * word_boost at ~1000 terms.
 */
export const PEDIATRIC_WORD_BOOST: ReadonlyArray<string> = [
  // --- Common peds diagnoses / problems ---
  'otitis media',
  'acute otitis media',
  'serous otitis media',
  'pharyngitis',
  'streptococcal pharyngitis',
  'tonsillitis',
  'bronchiolitis',
  'croup',
  'pneumonia',
  'sinusitis',
  'conjunctivitis',
  'gastroenteritis',
  'constipation',
  'reflux',
  'gastroesophageal reflux',
  'colic',
  'eczema',
  'atopic dermatitis',
  'molluscum',
  'impetigo',
  'cellulitis',
  'urticaria',
  'asthma',
  'reactive airway disease',
  'food allergy',
  'anaphylaxis',
  'failure to thrive',
  'hypothyroidism',
  'iron deficiency anemia',
  'lead poisoning',
  'enuresis',
  'encopresis',
  'ADHD',
  'attention deficit',
  'autism spectrum disorder',
  'anxiety',
  'depression',
  'concussion',
  'hand foot mouth disease',
  'roseola',
  'fifth disease',
  'scarlet fever',
  'mononucleosis',
  'COVID',
  'RSV',
  'influenza',
  'pertussis',
  'measles',
  'chickenpox',
  'varicella',
  'pinworms',
  'lice',
  'scabies',

  // --- Anatomy / exam findings ---
  'tympanic membrane',
  'otorrhea',
  'nasopharyngeal',
  'oropharyngeal',
  'cervical lymphadenopathy',
  'tonsillar exudate',
  'cobblestoning',
  'wheezing',
  'rhonchi',
  'crackles',
  'rales',
  'retractions',
  'grunting',
  'nasal flaring',
  'tachypnea',
  'tachycardia',
  'fontanelle',
  'umbilical',
  'hepatosplenomegaly',
  'abdomen',
  'rebound',
  'guarding',

  // --- Vital signs ---
  'temperature',
  'heart rate',
  'respiratory rate',
  'blood pressure',
  'oxygen saturation',
  'percentile',

  // --- Developmental / behavior ---
  'milestones',
  'developmental delay',
  'speech delay',
  'gross motor',
  'fine motor',
  'social emotional',
  'temper tantrums',
  'sleep regression',
  'night waking',
  'separation anxiety',
  'object permanence',

  // --- Vaccines ---
  'DTaP',
  'Tdap',
  'MMR',
  'MMRV',
  'varicella',
  'IPV',
  'polio',
  'Hib',
  'PCV13',
  'PCV15',
  'PCV20',
  'pneumococcal',
  'rotavirus',
  'hepatitis A',
  'hepatitis B',
  'HPV',
  'meningococcal',
  'MenACWY',
  'MenB',
  'influenza',
  'flu shot',
  'COVID-19 vaccine',
  'RSV vaccine',
  'nirsevimab',

  // --- Common peds medications ---
  'amoxicillin',
  'amoxicillin clavulanate',
  'augmentin',
  'azithromycin',
  'cefdinir',
  'cefixime',
  'cephalexin',
  'clindamycin',
  'penicillin',
  'oseltamivir',
  'tamiflu',
  'acyclovir',
  'albuterol',
  'fluticasone',
  'montelukast',
  'singulair',
  'budesonide',
  'cetirizine',
  'loratadine',
  'diphenhydramine',
  'benadryl',
  'epinephrine',
  'epipen',
  'auvi-q',
  'acetaminophen',
  'tylenol',
  'ibuprofen',
  'motrin',
  'advil',
  'methylphenidate',
  'concerta',
  'ritalin',
  'amphetamine',
  'adderall',
  'guanfacine',
  'clonidine',
  'sertraline',
  'fluoxetine',
  'melatonin',
  'polyethylene glycol',
  'miralax',
  'lactulose',
  'omeprazole',
  'famotidine',
  'ondansetron',
  'zofran',
  'dexamethasone',

  // --- Procedure / counseling terms ---
  'nebulizer',
  'spacer',
  'peak flow',
  'pulse oximetry',
  'rapid strep',
  'throat culture',
  'urinalysis',
  'CBC',
  'CMP',
  'lead level',
  'TSH',
  'CRP',
  'newborn screen',
  'audiology',
  'ophthalmology',
  'orthopedics',
  'dermatology',
  'gastroenterology',
  'pulmonology',
  'cardiology',
  'neurology',

  // --- Anticipatory guidance ---
  'anticipatory guidance',
  'safe sleep',
  'tummy time',
  'rear facing car seat',
  'breastfeeding',
  'formula feeding',
  'solid foods',
  'introduction of solids',
  'screen time',
  'sleep hygiene',
  'toilet training',
  'fluoride',
  'sunscreen',
  'helmet',
  'firearm safety',

  // --- Roles / titles you might mention ---
  'pediatrician',
  'NP',
  'nurse practitioner',
  'PA',
  'physician assistant',
  'school nurse',
  'guardian',
];
